export const ROUTES = {
  HOME:           "/",
  ACCREDITATION:  "/accreditation",
  ABOUT_INSTITUTE:"/about/institute",
  ABOUT_MISSION:  "/about/mission",
  ABOUT_POLICIES: "/about/policies",
  ABOUT_ADVISORY: "/about/advisory-board",
  ABOUT_REVIEW:   "/about/review-panel",
  CONTACT:        "/contact",
  MEMBERSHIP:     "/membership",
  COURSES:        "/courses",
  COURSE_DETAIL:  "/courses/:id",
  DASHBOARD:      "/dashboard",
  LOGIN:          "/login",
  SIGNUP:         "/signup",
} as const
